# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqnorm <- function(x) {
    .Call('yuima_sqnorm', PACKAGE = 'yuima', x)
}

makeprop <- function(mu, sample, low, up) {
    .Call('yuima_makeprop', PACKAGE = 'yuima', mu, sample, low, up)
}

W1 <- function(crossdx, b, A, h) {
    .Call('yuima_W1', PACKAGE = 'yuima', crossdx, b, A, h)
}

W2 <- function(dx, b, h) {
    .Call('yuima_W2', PACKAGE = 'yuima', dx, b, h)
}

detcpp <- function(A) {
    .Call('yuima_detcpp', PACKAGE = 'yuima', A)
}

Smake <- function(b, d) {
    .Call('yuima_Smake', PACKAGE = 'yuima', b, d)
}

solvecpp <- function(A) {
    .Call('yuima_solvecpp', PACKAGE = 'yuima', A)
}

sub_f <- function(S, b) {
    .Call('yuima_sub_f', PACKAGE = 'yuima', S, b)
}

likndim <- function(dx, b, A, h) {
    .Call('yuima_likndim', PACKAGE = 'yuima', dx, b, A, h)
}

