# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evalKernelCpp <- function(Integrand2, Integrand2expr, myenvd1, myenvd2, ExistdN, ExistdX, gridTime, dimCol, NameCol, JumpTimeName) {
    .Call('_yuima_evalKernelCpp', PACKAGE = 'yuima', Integrand2, Integrand2expr, myenvd1, myenvd2, ExistdN, ExistdX, gridTime, dimCol, NameCol, JumpTimeName)
}

evalKernelCpp2 <- function(Integrand2, Integrand2expr, myenvd1, myenvd2, CondIntensity, NameCountingVar, Namecovariates, ExistdN, ExistdX, gridTime, dimCol, NameCol, JumpTimeName) {
    .Call('_yuima_evalKernelCpp2', PACKAGE = 'yuima', Integrand2, Integrand2expr, myenvd1, myenvd2, CondIntensity, NameCountingVar, Namecovariates, ExistdN, ExistdX, gridTime, dimCol, NameCol, JumpTimeName)
}

sqnorm <- function(x) {
    .Call('_yuima_sqnorm', PACKAGE = 'yuima', x)
}

makeprop <- function(mu, sample, low, up) {
    .Call('_yuima_makeprop', PACKAGE = 'yuima', mu, sample, low, up)
}

is_zero <- function(x) {
    .Call('_yuima_is_zero', PACKAGE = 'yuima', x)
}

cpp_split <- function(str, sep) {
    .Call('_yuima_cpp_split', PACKAGE = 'yuima', str, sep)
}

cpp_paste <- function(x, y, sep) {
    .Call('_yuima_cpp_paste', PACKAGE = 'yuima', x, y, sep)
}

cpp_collapse <- function(str, sep) {
    .Call('_yuima_cpp_collapse', PACKAGE = 'yuima', str, sep)
}

cpp_outer <- function(x, y) {
    .Call('_yuima_cpp_outer', PACKAGE = 'yuima', x, y)
}

cpp_ito_outer <- function(x, y) {
    .Call('_yuima_cpp_ito_outer', PACKAGE = 'yuima', x, y)
}

cpp_label <- function(I) {
    .Call('_yuima_cpp_label', PACKAGE = 'yuima', I)
}

cpp_ito_product <- function(idx, dZ, Z_K, K, d, a, p, q = 0L) {
    .Call('_yuima_cpp_ito_product', PACKAGE = 'yuima', idx, dZ, Z_K, K, d, a, p, q)
}

cpp_E <- function(str) {
    .Call('_yuima_cpp_E', PACKAGE = 'yuima', str)
}

cpp_ito <- function(K_set, dZ, Z_K, d, r) {
    .Call('_yuima_cpp_ito', PACKAGE = 'yuima', K_set, dZ, Z_K, d, r)
}

calc_kalman_bucy_filter_cpp <- function(un_dr_sl, un_dr_in, un_diff, ob_dr_sl, ob_dr_in, inv_sq_ob_diff, vcov_init, mean_init, delta, deltaY, use_are, is_explicit, is_time_homogeneous, calc_minuslogl, drop_terms, upsump_rate = 1L) {
    .Call('_yuima_calc_kalman_bucy_filter_cpp', PACKAGE = 'yuima', un_dr_sl, un_dr_in, un_diff, ob_dr_sl, ob_dr_in, inv_sq_ob_diff, vcov_init, mean_init, delta, deltaY, use_are, is_explicit, is_time_homogeneous, calc_minuslogl, drop_terms, upsump_rate)
}

W1 <- function(crossdx, b, A, h) {
    .Call('_yuima_W1', PACKAGE = 'yuima', crossdx, b, A, h)
}

W2 <- function(dx, b, h) {
    .Call('_yuima_W2', PACKAGE = 'yuima', dx, b, h)
}

Irregular_PseudoLoglik_COG <- function(lengthObs, B, Btilde, InvBtilde, a0, bq, a1, V, PseudologLik, ta, state, stateMean, e, DeltaG2, Deltat) {
    .Call('_yuima_Irregular_PseudoLoglik_COG', PACKAGE = 'yuima', lengthObs, B, Btilde, InvBtilde, a0, bq, a1, V, PseudologLik, ta, state, stateMean, e, DeltaG2, Deltat)
}

minusloglcpp_linear_state_space_theta1 <- function(logdet_sq_ob_diff, inv_sq_ob_diff, deltaY, delta) {
    .Call('_yuima_minusloglcpp_linear_state_space_theta1', PACKAGE = 'yuima', logdet_sq_ob_diff, inv_sq_ob_diff, deltaY, delta)
}

calc_inverse_square <- function(cube) {
    .Call('_yuima_calc_inverse_square', PACKAGE = 'yuima', cube)
}

driftTermCpp <- function(drift, modelstate, data, env) {
    .Call('_yuima_driftTermCpp', PACKAGE = 'yuima', drift, modelstate, data, env)
}

diffusionTermCpp <- function(diffusion, modelstate, data, env) {
    .Call('_yuima_diffusionTermCpp', PACKAGE = 'yuima', diffusion, modelstate, data, env)
}

measureTermCpp <- function(measure, modelstate, data, env) {
    .Call('_yuima_measureTermCpp', PACKAGE = 'yuima', measure, modelstate, data, env)
}

detcpp <- function(A) {
    .Call('_yuima_detcpp', PACKAGE = 'yuima', A)
}

Smake <- function(b, d) {
    .Call('_yuima_Smake', PACKAGE = 'yuima', b, d)
}

solvecpp <- function(A) {
    .Call('_yuima_solvecpp', PACKAGE = 'yuima', A)
}

sub_f <- function(S, b) {
    .Call('_yuima_sub_f', PACKAGE = 'yuima', S, b)
}

likndim <- function(dx, b, A, h) {
    .Call('_yuima_likndim', PACKAGE = 'yuima', dx, b, A, h)
}

residualCpp <- function(dx, a, b, w, h) {
    .Call('_yuima_residualCpp', PACKAGE = 'yuima', dx, a, b, w, h)
}

